### ISSUE TITLE
[ultra low severity] Mistake in the error message

### ISSUE THREAD

**Issue by TomKulakov** [Flank/gcloud_cli#18]
https://github.com/Flank/gcloud_cli/blob/a94296b5b2bf097fe7b3dcd145921aa07cfd8079/google-cloud-sdk/lib/googlecloudsdk/command_lib/scc/bqexports/request_hooks.py#L97

Just got this error.
I bet it was supposed to say "BigQuery" :)

**Comment by adamvduke** [comment]
Thanks for filing the issue. This appears to be a repository intended to track the upstream changes in the gcloud cli, and upstream would be the appropriate place to fix this. I'm going to close this issue and archive the repository for now.
